apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datarepo-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
data:
  nginxconf: |-
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;
      include /etc/nginx/mime.types;
      server_tokens off;
    
      # Needed for chunked responses (for oauth2 proxying)
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    
      server { # simple reverse-proxy
        listen       {{ .Values.nginxport }};

        # add a Content-Security-Policy, with some variables to make formatting nice
        set $DEFAULT "default-src 'self'";
        set $SCRIPT "script-src 'self' 'unsafe-inline' apis.google.com *.gstatic.com *.broadinstitute.org *.terra.bio *.envs-terra.bio *.fontawesome.com";
        set $STYLE "style-src 'self' 'unsafe-inline' fonts.googleapis.com";
        set $IMG "img-src 'self' data: *.googleusercontent.com *.terra.bio *.envs-terra.bio";
        set $FONT "font-src 'self' fonts.googleapis.com fonts.gstatic.com";
        set $CONNECT "connect-src 'self' *.envs-terra.bio *.broadinstitute.org account.google.com *.googleapis.com *.fontawesome.com";
        set $FRAME "frame-src 'self' accounts.google.com";
        add_header Content-Security-Policy "${DEFAULT}; ${SCRIPT}; ${STYLE}; ${IMG}; ${FONT}; ${CONNECT}; ${FRAME}";

        # pass the status check through
        location /status {
            proxy_pass {{ .Values.proxyPass.status }};
        }

        # get swagger working
        location /swagger-ui.html {
            proxy_pass {{ .Values.proxyPass.swagger }};
        }

        location ~ (configuration|ga4gh|webjars|api-docs|data-repository-openapi|swagger-resources|oauth2) {
            proxy_pass {{ .Values.proxyPass.api }};
        }

        # serve static files
        location / {
          root /usr/share/nginx/html;
          try_files $uri /index.html =404;
        }
      }
    }
