{{- $hasCredentials := include "install-secrets-manager.hasCredentials" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: {{ .Chart.Name }}
    {{- include "install-secrets-manager.labels" . | nindent 4 }}
  name: {{ include "install-secrets-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: install-secrets-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: install-secrets-manager
    spec:
      serviceAccountName: {{ template "install-secrets-manager.serviceAccountName" . }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: IfNotPresent
        name: {{ .Chart.Name }}
        args:
        - -vault.engine={{ .Values.vaultVersion }}
        {{ if $hasCredentials -}}
        env:
        - name: VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "install-secrets-manager.secretName" . }}
              key: {{ include "install-secrets-manager.secretKeyRoleId" . }}
        - name: VAULT_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "install-secrets-manager.secretName" . }}
              key: {{ include "install-secrets-manager.secretKeySecretId" . }}
        {{ end -}}
        - name: VAULT_ADDR
          value: {{ .Values.vaultLocation }}
